const firebaseConfig={apiKey:"AIzaSyCtuUMTbByy39KxAbLdw5GUkO_cHmfZHHc",authDomain:"boodschappenthuis1.firebaseapp.com",databaseURL:"https://boodschappenthuis1-default-rtdb.firebaseio.com",projectId:"boodschappenthuis1",storageBucket:"boodschappenthuis1.firebasestorage.app",messagingSenderId:"845995010779",appId:"1:845995010779:web:5896c89bde8b3ace507afe"};
firebase.initializeApp(firebaseConfig);const auth=firebase.auth(),db=firebase.database();auth.setPersistence(firebase.auth.Auth.Persistence.LOCAL).catch(console.error);
let state={items:[],saved:[],householdId:null,sharedId:null,sharedCode:null,active:"family",screen:0,sharedUnsub:null};
const catalog=[['Melk','🥛'],['Brood','🍞'],['Eieren','🥚'],['Kaas','🧀'],['Boter','🧈'],['Yoghurt','🥣'],['Appels','🍎'],['Bananen','🍌'],['Tomaten','🍅'],['Komkommer','🥒'],['Aardappelen','🥔'],['Uien','🧅'],['Kip','🍗'],['Rijst','🍚'],['Pasta','🍝'],['Koffie','☕'],['Thee','🍵'],['Water','💧'],['Chips','🥔'],['Wc-papier','🧻']];
const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2200)}
function go(i){state.screen=i;$('track').style.transform=`translateX(-${i*100}%)`;document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',+b.dataset.i===i));if(i===1)renderFamily();if(i===2)renderSaved();if(i===3)renderSettings()}
function openDrawer(){$('drawerWrap').classList.add('show')}function closeDrawer(){$('drawerWrap').classList.remove('show')}
function openModal(title,body){$('mTitle').textContent=title;$('mBody').innerHTML=body;$('modal').classList.add('show')}function closeModal(){$('modal').classList.remove('show')}
function normalize(arr){return (Array.isArray(arr)?arr:[]).map((x,i)=>typeof x==='string'?{name:x,done:false,id:'legacy-'+i}:({...x,id:x.id||crypto.randomUUID()}))}
function currentPath(){if(state.active==='shared'&&state.sharedId)return db.ref(`sharedLists/${state.sharedId}/boodschappen`);if(state.householdId)return db.ref(`households/${state.householdId}/boodschappen`);return null}
async function saveItems(){const ref=currentPath();if(ref)await ref.set(state.items);else localStorage.setItem('boodschappenPrivate_'+auth.currentUser.uid,JSON.stringify(state.items))}
function renderSuggestions(){const box=$('suggestions');if(!box)return;const names=catalog.slice(0,10);box.innerHTML=names.map(x=>`<button class="suggestion" onclick="addSuggested('${esc(x[0])}')"><span>${x[1]}</span>${esc(x[0])}</button>`).join('')}
function renderList(){const q=$('search').value.trim().toLowerCase();const shown=state.items.filter(x=>x.name.toLowerCase().includes(q));$('count').textContent=state.items.filter(x=>!x.done).length;const box=$('items');if(!shown.length){box.innerHTML='<div class="empty">Je lijst is nog leeg.<br><br>Voeg bovenaan je eerste product toe.</div>';return}box.innerHTML=shown.map(x=>`<div class="item ${x.done?'done':''}"><button class="check" onclick="toggleItem('${x.id}')">${x.done?'✓':''}</button><div class="itemIcon">${esc(x.icon||'🛒')}</div><div class="itemName">${esc(x.name)}<div class="meta">${x.done&&x.completedBy?'Afgerond door '+esc(x.completedBy):'Nog te doen'}</div></div><div class="itemActions"><button class="edit" onclick="editItem('${x.id}')">✎</button><button class="trash" onclick="removeItem('${x.id}')">⌫</button></div></div>`).join('')}
async function addSuggested(name){const product=catalog.find(x=>x[0]===name);if(!product)return;state.items.push({id:crypto.randomUUID(),name:product[0],icon:product[1],done:false});await saveItems();renderList();toast(product[0]+' toegevoegd')}
async function editItem(id){const x=state.items.find(x=>x.id===id);if(!x)return;const name=prompt('Product aanpassen',x.name);if(name===null)return;const clean=name.trim();if(!clean)return toast('Vul een productnaam in');x.name=clean;await saveItems();renderList();toast('Product aangepast')}
async function addItem(){const input=$('newItem'),name=input.value.trim();if(!name)return;const product=catalog.find(x=>x[0].toLowerCase()===name.toLowerCase());state.items.push({id:crypto.randomUUID(),name:product?product[0]:name,icon:product?.[1]||'🛒',done:false});input.value='';await saveItems();renderList()}
async function toggleItem(id){const x=state.items.find(x=>x.id===id);if(!x)return;x.done=!x.done;x.completedBy=x.done?(auth.currentUser?.displayName||auth.currentUser?.email||'Jij'):'';await saveItems();renderList()}
async function removeItem(id){state.items=state.items.filter(x=>x.id!==id);await saveItems();renderList()}
async function clearDone(){state.items=state.items.filter(x=>!x.done);await saveItems();renderList()}
async function saveCurrentList(){if(!state.items.length)return toast('Je lijst is leeg');state.saved.unshift({name:'Boodschappen '+new Date().toLocaleDateString('nl-NL'),items:JSON.parse(JSON.stringify(state.items)),createdAt:Date.now()});localStorage.setItem('savedLists',JSON.stringify(state.saved));renderSaved();toast('Lijst opgeslagen')}
function renderSaved(){const box=$('saved');if(!state.saved.length){box.innerHTML='<div class="empty">Nog geen opgeslagen lijsten.</div>';return}box.innerHTML=state.saved.map((x,i)=>`<div class="item"><div class="itemName">${esc(x.name)}<div class="meta">${x.items.length} producten</div></div><button class="secondary" onclick="loadSaved(${i})">Open</button></div>`).join('')}
async function loadSaved(i){state.items=normalize(state.saved[i].items);state.active='private';await saveItems();go(0);renderList();toast('Lijst geopend')}
async function getHousehold(){const u=auth.currentUser;if(!u)return null;const snap=await db.ref(`users/${u.uid}/householdId`).once('value');const id=snap.val();if(!id)return null;const hs=await db.ref(`households/${id}`).once('value');if(!hs.exists()){await db.ref(`users/${u.uid}/householdId`).remove();return null}const h=hs.val()||{};if(h.owner!==u.uid&&!(h.members&&h.members[u.uid]))return null;state.householdId=String(id);return state.householdId}
async function loadFamily(){state.active='family';state.sharedId=null;if(state.sharedUnsub){state.sharedUnsub();state.sharedUnsub=null}const ref=currentPath();if(ref){const s=await ref.once('value');state.items=normalize(s.val()||[])}else state.items=normalize(JSON.parse(localStorage.getItem('boodschappenPrivate_'+auth.currentUser.uid)||'[]'));renderList()}
async function renderFamily(){const u=auth.currentUser;if(!u){$('familySub').textContent='Log in om je familielijst te gebruiken.';$('familyCard').innerHTML='<button class="primary" style="width:100%;height:54px" onclick="openLogin()">Inloggen</button>';return}const h=state.householdId?await db.ref(`households/${state.householdId}`).once('value'):null;const v=h?.val()||{};const members=v.members?Object.keys(v.members).filter(k=>v.members[k]===true):[];$('familySub').textContent=state.householdId?'Jouw gezamenlijke boodschappenlijst.':'Je hebt nog geen familie.';$('familyCard').innerHTML=`<div class="member"><div class="memberIcon">👥</div><div style="flex:1"><b>${state.householdId?'Familielijst':'Geen familie ingesteld'}</b><div class="meta">${members.length||(!state.householdId?0:1)} leden</div></div></div>${state.householdId?`<button class="secondary" style="width:100%;margin-top:10px" onclick="loadFamily();go(0)">Familielijst openen</button>`:`<button class="primary" style="width:100%;height:54px;margin-top:10px" onclick="familySetup()">Familie instellen</button>`}`}
async function familySetup(){const u=auth.currentUser;if(!u)return openLogin();await openUseModeModal()}
async function createNewFamily(){const u=auth.currentUser;if(!u)return;try{let existing=await getHousehold();if(existing){state.householdId=existing;closeUseModeModal();await loadFamily();go(0);return}let code=null,created=false,lastErr=null;for(let i=0;i<8&&!created;i++){code=String(Math.floor(100000+Math.random()*900000));try{await db.ref(`households/${code}`).set({owner:u.uid,name:'Mijn familie',members:{[u.uid]:true},memberNames:{[u.uid]:u.displayName||u.email||'Lid'},boodschappen:[]});created=true}catch(e){lastErr=e}}if(!created)throw lastErr||new Error('Familie kon niet worden aangemaakt.');await db.ref(`users/${u.uid}/householdId`).set(code);state.householdId=code;localStorage.setItem('boodschappenUseMode_'+u.uid,'family');closeUseModeModal();await loadFamily();renderFamily();go(0);openModal('Nieuwe familie aangemaakt',`<p>Je nieuwe familie is aangemaakt.</p><div class="code">${esc(code)}</div><p>Dit is je familiecode. Deel deze code met de mensen die je wilt toevoegen.</p>`)}catch(e){console.error(e);toast(e.message||'Nieuwe familie aanmaken mislukt')}}
async function enterFamilyCode(){const u=auth.currentUser;if(!u)return;openModal('Familiecode invoeren',`<p>Voer de 6-cijferige familiecode in.</p><div class="field"><input id="familyCodeInput" inputmode="numeric" maxlength="6" placeholder="6 cijfers"></div><div class="actions"><button class="secondary" onclick="closeModal();openUseModeModal()">Terug</button><button class="primary" style="height:44px" onclick="joinFamilyByCode()">Doorgaan</button></div>`)}
async function joinFamilyByCode(){const u=auth.currentUser,code=($('familyCodeInput')?.value||'').trim();if(!/^\d{6}$/.test(code))return toast('Vul een geldige 6-cijferige familiecode in');try{const ref=db.ref(`households/${code}`),snap=await ref.once('value');if(!snap.exists())throw new Error('Deze familiecode bestaat niet.');const h=snap.val()||{};await ref.child(`members/${u.uid}`).set(true);await ref.child(`memberNames/${u.uid}`).set(u.displayName||u.email||'Lid');await db.ref(`users/${u.uid}/householdId`).set(code);state.householdId=code;localStorage.setItem('boodschappenUseMode_'+u.uid,'family');closeModal();closeUseModeModal();await loadFamily();renderFamily();go(0);toast('Je bent toegevoegd aan de familie')}catch(e){toast(e.message||'Familiecode invoeren mislukt')}}
async function leaveFamily(){const u=auth.currentUser;if(!u||!state.householdId)return toast('Je zit niet in een familie');if(!confirm('Weet je zeker dat je de familie wilt verlaten?'))return;await db.ref(`households/${state.householdId}/members/${u.uid}`).remove();await db.ref(`users/${u.uid}/householdId`).remove();state.householdId=null;await loadFamily();renderFamily();toast('Je hebt de familie verlaten')}
async function openSharedMenu(){closeDrawer();const u=auth.currentUser;if(!u)return openLogin();const snap=await db.ref(`userSharedLists/${u.uid}`).once('value');const ids=Object.keys(snap.val()||{});let rows='<button class="primary" style="height:50px;width:100%;margin-bottom:12px" onclick="newSharedList()">＋ Nieuwe deellijst</button>';if(!ids.length)rows+='<div class="empty">Nog geen deellijsten.</div>';else for(const id of ids){const s=await db.ref(`sharedLists/${id}`).once('value'),v=s.val();if(v)rows+=`<button class="menuBtn" style="margin-bottom:8px" onclick="openSharedList('${id}')"><i class="mi">↗</i>${esc(v.name||'Deellijst')}<span>›</span></button>`}openModal('Deellijsten',rows)}
async function newSharedList(){const name=prompt('Naam van de deellijst');if(!name?.trim())return;const u=auth.currentUser,ref=db.ref('sharedLists').push(),id=ref.key;let code;do{code=String(Math.floor(100000+Math.random()*900000));}while((await db.ref(`sharedListCodes/${code}`).once('value')).exists());const data={name:name.trim(),owner:u.uid,members:{[u.uid]:true},memberNames:{[u.uid]:u.displayName||u.email||'Lid'},inviteCode:code,boodschappen:[]};await ref.set(data);await db.ref(`sharedListCodes/${code}`).set(id);await db.ref(`userSharedLists/${u.uid}/${id}`).set(true);closeModal();await openSharedList(id);toast('Deellijst aangemaakt')}
async function openSharedList(id){const u=auth.currentUser;if(!u)return openLogin();if(state.sharedUnsub){state.sharedUnsub();state.sharedUnsub=null}const s=await db.ref(`sharedLists/${id}`).once('value'),v=s.val();if(!v||v.members?.[u.uid]!==true)return toast('Je hebt geen toegang');state.active='shared';state.sharedId=id;state.sharedCode=v.inviteCode||null;state.items=normalize(v.boodschappen||[]);const ref=db.ref(`sharedLists/${id}/boodschappen`);const fn=ss=>{state.items=normalize(ss.val()||[]);renderList()};ref.on('value',fn);state.sharedUnsub=()=>ref.off('value',fn);closeModal();go(0);toast(v.name||'Deellijst geopend')}
async function showSharedInfo(){if(!state.sharedId)return;const s=await db.ref(`sharedLists/${state.sharedId}`).once('value'),v=s.val()||{};const ids=Object.keys(v.members||{}).filter(k=>v.members[k]);let members=ids.map(id=>`<div class="member"><div class="memberIcon">${id===v.owner?'👑':'👤'}</div><div>${esc(v.memberNames?.[id]||'Lid')}</div></div>`).join('');openModal('Deellijst',`<p><b>${esc(v.name||'Deellijst')}</b></p><div class="code">${esc(v.inviteCode||'')}</div><button class="primary" style="width:100%;height:50px" onclick="navigator.clipboard.writeText('${esc(v.inviteCode||'')}');toast('Deelcode gekopieerd')">Kopiëren</button><h3>Leden (${ids.length})</h3>${members}`)}
function openSettingsMenu(){closeDrawer();go(3)}function openAbout(){closeDrawer();openModal('Over de app','<p>Een nieuwe Boodschappenlijst, vanaf nul opgebouwd. De vormgeving en navigatie zijn nieuw; Firebase blijft de basis voor accounts, families en gedeelde lijsten.</p><p>Versie 1.0</p>')}
function renderSettings(){const u=auth.currentUser;$('accountSub').textContent=u?(u.displayName||u.email||'Ingelogd'):'Nog niet ingelogd.';$('settingsCard').innerHTML=u?`<div class="member"><div class="memberIcon">👤</div><div style="flex:1"><b>${esc(u.displayName||'Account')}</b><div class="meta">${esc(u.email||'')}</div></div></div><button class="secondary" style="width:100%;margin-top:10px" onclick="showSharedInfo()">Actieve deellijst</button><button class="secondary" style="width:100%;margin-top:8px" onclick="logout()">Uitloggen</button>`:'<div class="empty">Log in om je account en instellingen te beheren.</div>'}
async function login(){const email=$('email').value.trim(),pass=$('password').value;if(!email||!pass)return toast('Vul je e-mailadres en wachtwoord in');try{await auth.signInWithEmailAndPassword(email,pass);toast('Welkom terug')}catch(e){let m='Inloggen is niet gelukt.';if(e.code==='auth/invalid-credential'||e.code==='auth/wrong-password')m='E-mailadres of wachtwoord is onjuist.';else if(e.code==='auth/user-not-found')m='Er bestaat geen account met dit e-mailadres.';else if(e.code==='auth/invalid-email')m='Het e-mailadres is niet geldig.';toast(m)}}
function openRegister(){$('registerModal').classList.add('show')}function closeRegister(){$('registerModal').classList.remove('show')}function closeSuccessModal(){$('successModal').classList.remove('show');$('successModal').setAttribute('aria-hidden','true');$('loginScreen').classList.remove('hidden')}
async function register(){const name=($('registerName').value||'').trim(),email=($('registerEmail').value||'').trim(),pass=$('registerPassword').value||'',confirmPass=$('registerPasswordConfirm').value||'';if(!name||!email||!pass||!confirmPass)return toast('Vul alle velden in');if(pass!==confirmPass)return toast('De wachtwoorden komen niet overeen');if(pass.length<6)return toast('Het wachtwoord moet minimaal 6 tekens bevatten');try{const c=await auth.createUserWithEmailAndPassword(email,pass);await db.ref(`users/${c.user.uid}`).set({email:c.user.email,name});await auth.signOut();['registerName','registerEmail','registerPassword','registerPasswordConfirm'].forEach(id=>$(id).value='');closeRegister();$('loginScreen').classList.remove('hidden');$('successModal').classList.add('show');$('successModal').setAttribute('aria-hidden','false')}catch(e){let m='Account aanmaken mislukt.';if(e.code==='auth/email-already-in-use')m='Dit e-mailadres is al in gebruik.';else if(e.code==='auth/invalid-email')m='Vul een geldig e-mailadres in.';else if(e.code==='auth/weak-password')m='Het wachtwoord is te zwak. Gebruik minimaal 6 tekens.';toast(m)}}
async function resetPassword(){const email=$('email').value.trim();if(!email)return toast('Vul eerst je e-mailadres in');try{await auth.sendPasswordResetEmail(email);toast('Er is een e-mail gestuurd om je wachtwoord opnieuw in te stellen.')}catch(e){toast('Wachtwoord resetten mislukt')}}
function openLogin(){$('loginScreen').classList.remove('hidden')}
function openUseModeModal(){$('useModeModal').classList.add('show');$('useModeModal').setAttribute('aria-hidden','false')}function closeUseModeModal(){$('useModeModal').classList.remove('show');$('useModeModal').setAttribute('aria-hidden','true')}
async function chooseUseMode(mode){const u=auth.currentUser;if(!u)return;if(mode==='family')return createNewFamily();if(mode==='code')return enterFamilyCode();if(mode==='private'){state.active='private';state.householdId=null;localStorage.setItem('boodschappenUseMode_'+u.uid,'private');closeUseModeModal();await loadPrivateList();go(0);toast('Privélijst geopend')}}
async function loadPrivateList(){const u=auth.currentUser;if(!u)return;try{state.items=normalize(JSON.parse(localStorage.getItem('boodschappenPrivate_'+u.uid)||'[]'));state.active='private';state.householdId=null;state.sharedId=null;renderList()}catch(e){state.items=[];renderList()}}
async function logout(){if(state.sharedUnsub)state.sharedUnsub();state={...state,items:[],householdId:null,sharedId:null,sharedCode:null,active:'family'};await auth.signOut();openLogin();renderSettings();toast('Uitgelogd')}
auth.onAuthStateChanged(async u=>{if(u){$('loginScreen').classList.add('hidden');try{const code=new URLSearchParams(location.search).get('deellijst');if(code){await joinByInvite(code);return}const household=await getHousehold();if(household){state.active='family';await loadFamily()}else{const mode=localStorage.getItem('boodschappenUseMode_'+u.uid);if(mode==='private'){await loadPrivateList()}else{state.items=[];renderList();openUseModeModal()}}}catch(e){console.error(e)}renderSettings();renderFamily()}else{$('loginScreen').classList.remove('hidden');state.householdId=null;state.active='private';state.items=[];renderList();renderSettings();renderFamily()}});
async function joinByInvite(code){try{const s=await db.ref(`sharedListCodes/${code}`).once('value'),id=s.val();if(!id)return toast('Deze uitnodigingslink is niet geldig');const l=await db.ref(`sharedLists/${id}`).once('value'),v=l.val();if(v.members?.[auth.currentUser.uid]!==true){if(!confirm(`Deelnemen aan “${v.name}”?`))return;await db.ref(`sharedLists/${id}/members/${auth.currentUser.uid}`).set(true);await db.ref(`sharedLists/${id}/memberNames/${auth.currentUser.uid}`).set(auth.currentUser.email||'Lid');await db.ref(`userSharedLists/${auth.currentUser.uid}/${id}`).set(true)}await openSharedList(id)}catch(e){toast('Uitnodiging kon niet worden verwerkt')}}
function bindAuthButtons(){
  $('loginBtn')?.addEventListener('click',login);
  $('openRegisterBtn')?.addEventListener('click',openRegister);
  $('closeRegisterBtn')?.addEventListener('click',closeRegister);
  $('registerBtn')?.addEventListener('click',register);
  $('successCloseBtn')?.addEventListener('click',closeSuccessModal);
}
$('newItem').addEventListener('keydown',e=>{if(e.key==='Enter')addItem()});
$('items').addEventListener('click',e=>{});
bindAuthButtons();
renderSuggestions();renderList();state.saved=JSON.parse(localStorage.getItem('savedLists')||'[]');renderSaved();


// --- Nieuwe registratieflow ---
function openRegister(){
  const m=document.getElementById('registerModal');
  if(m) m.classList.remove('hidden');
  const e=document.getElementById('registerError'); if(e) e.textContent='';
}
function closeRegister(){
  const m=document.getElementById('registerModal');
  if(m) m.classList.add('hidden');
}
async function registerUser(){
  const name=(document.getElementById('regName')?.value||'').trim();
  const email=(document.getElementById('regEmail')?.value||'').trim();
  const p1=document.getElementById('regPassword')?.value||'';
  const p2=document.getElementById('regPassword2')?.value||'';
  const err=document.getElementById('registerError');
  if(err) err.textContent='';
  if(!name || !email || !p1 || !p2){ if(err) err.textContent='Vul alle velden in.'; return; }
  if(p1!==p2){ if(err) err.textContent='De wachtwoorden komen niet overeen.'; return; }
  if(p1.length<6){ if(err) err.textContent='Het wachtwoord moet minimaal 6 tekens bevatten.'; return; }
  try{
    if(typeof createUserWithEmailAndPassword!=='function'){
      throw new Error('Registratie is nog niet gekoppeld aan Firebase Authentication.');
    }
    const cred=await createUserWithEmailAndPassword(auth,email,p1);
    if(typeof setDoc==='function' && typeof doc==='function'){
      await setDoc(doc(db,'users',cred.user.uid),{
        name:name,
        email:email,
        householdId:null,
        useMode:null
      },{merge:true});
    }
    await signOut(auth);
    closeRegister();
    alert('Account succesvol aangemaakt. Je kunt nu inloggen.');
    document.querySelectorAll('#loginScreen input').forEach(i=>i.value='');
  }catch(e){
    if(err) err.textContent=e?.message||'Account aanmaken is niet gelukt.';
  }
}
